version: '3.1'
services:
  mysql-db:
    image: mysql:8.0.28
    environment:
      MYSQL_DATABASE: springulardb
      MYSQL_USER: springuser
      MYSQL_PASSWORD: userpassword
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3307:3306"

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mysql-db
    environment:
      SPRING_PROFILES_ACTIVE: docker

volumes:
  db-data:
